
//timestamp server
export const GET_COMPILATION_DATA = "GET_COMPILATION_DATA"
export const NEW_COMPILATION_DATA = "NEW_COMPILATION_DATA"

//ui actions 
export const UPDATE_SIDENAV_EXPANDED = "UPDATE_SIDENAV_EXPANDED"
export const GET_TABS = "GET_TABS"